import ProjectDescription

let workspace = Workspace(
    name: "DevLog",
    projects: [
        "Application/App",
        "Application/Core",
        "Application/Data",
        "Application/Domain",
        "Application/Infra",
        "Application/Persistence",
        "Application/Presentation",
        "Application/Widget",
        "Libraries/CollectionUI",
        "Libraries/MarkdownRenderer",
        "Widget/WidgetCore",
        "Widget/WidgetExtension",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        lastXcodeUpgradeCheck: "26.5.0"
    )
)
