default_platform(:ios)

platform :ios do
  private_lane :asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_PATH"],
      in_house: false
    )
  end

  lane :beta do
    apiKey = asc_api_key

    if ENV["CI"]
      setup_ci
    end

    if ENV["GITHUB_RUN_NUMBER"]
      increment_build_number(
        xcodeproj: "DevLog.xcodeproj",
        build_number: ENV["GITHUB_RUN_NUMBER"]
      )
    end

    match(
      api_key: apiKey,
      type: "appstore",
      readonly: ENV["CI"] == "true"
    )

    build_app(
      project: "DevLog.xcodeproj",
      scheme: "DevLog",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: apiKey,
      skip_waiting_for_build_processing: true
    )
  end

  lane :release do
    apiKey = asc_api_key

    if ENV["CI"]
      setup_ci
    end

    if ENV["GITHUB_RUN_NUMBER"]
      increment_build_number(
        xcodeproj: "DevLog.xcodeproj",
        build_number: ENV["GITHUB_RUN_NUMBER"]
      )
    end

    match(
      api_key: apiKey,
      type: "appstore",
      readonly: ENV["CI"] == "true"
    )

    build_app(
      project: "DevLog.xcodeproj",
      scheme: "DevLog",
      export_method: "app-store"
    )

    upload_to_app_store(
      api_key: apiKey,
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: true,
      automatic_release: false
    )
  end
end
